### ISSUE TITLE
CLUT mv3 does not function correctly.

### ISSUE THREAD

**Issue by petebrag** [harshayburadkar/clut-chrome-extension#20]
Hi, I'm talking about the new version (not the old one that got removed from Chrome Store) it does not work - there's no way to have an actual consistent moving to last recent tabs. Is this me? I've tried every combination of the keyboard shortcuts.

### IMPORTANT!!! 

Update from extension author (28 March 2025):
The latest version 2.1 fixes the issue.

**Comment by y-lee** [comment]
I am seeing the same thing, on Edge. The behavior has changed; when I hit the Quick switch keybinding, sometimes the extension jumps to the rightmost tab, not the actual previous tab.

**Comment by y-lee** [comment]
More detail: When this happens, and I jump back to the original tab, then use the shortcut twice quickly, the extension jumps to the penultimate tab. If I return to the original tab, then use the shortcut again three times quickly, the extension jumps to the second to last tab. And so forth.

Of course, those tabs were not actually visited by me recently. It's like, after a while (maybe 30 seconds), the extension's list of previously visited tabs gets overwritten by the list of all tabs, starting with the rightmost one.

**Comment by y-lee** [comment]
30 seconds are sufficient to trigger above behavior; did not try shorter times. Also, when using the Quick switch keybinding, if it's used again right after jumping to the rightmost tab, the extension jumps to the penultimate tab, which is more confirmation of what I said about how it's like the extension's list of previously visited tabs gets forgotten, or overwritten by the list of all tabs.

**Comment by PlagueCZ** [comment]
I can confirm y-lee's description. I only ever use the quick switch (been using this extension for ages now). 
This happens on all versions of Chrome I have, 134.0.6998.36, 136.x and also one old one at work where I still have the download bar.

**Comment by petebrag** [comment]
Here's what Perplexity has to say about this: Based on recent reports, there have been several issues with Chrome's tab functionality, affecting both native features and extensions. Here's an overview of the situation:

1. Tab Group Recall Issues: A recent Chrome update has disrupted the Tab Group feature, causing the loss of tabs when closing and reopening windows containing Tab Groups. This particularly affects tabs from extensions, such as suspended tabs or those paused during loading[2].

2. Form with Tabs Malfunction: Some users reported that forms using tabs stopped working after updating to Chrome version 115.0.5790.99. This issue affected specific forms and was not present in other browsers or older Chrome versions[3].

3. Empty Tabs Bug: Google addressed a bug where webpages would temporarily disappear when switching between open Chrome tabs. This issue has been fixed with a server-side update[4].

4. Tab Organizer Feature: Chrome introduced a new tab organizer feature that automatically suggests and creates tab groups based on open tabs. While this is a new functionality, it might interfere with existing tab management extensions[5].

5. Extension Compatibility Issues: Some tab management extensions, like Tabs Outliner, have been experiencing increasing difficulties with opening stored tabs after recent Chrome updates. This could be related to conflicts with Chrome's new tab features[6].

To address these issues, users can try the following:

- Disable the #tab-save-v flag in chrome://flags to restore Tab Group recall functionality[2].
- Clear browser cache and check for Chrome updates[3].
- Restart Chrome to apply any server-side updates[4].
- Consider using alternative browsers temporarily if the issues persist[7].

It's likely that these problems are a result of recent changes in Chrome's tab management system, and Google may be working on further updates to resolve compatibility issues with extensions and improve overall tab functionality.

Citations:
[1] https://www.windowslatest.com/2025/01/24/after-microsoft-edge-chrome-tests-a-split-tabs-feature/
[2] https://www.reddit.com/r/chrome/comments/1i0gzyd/on_the_recent_event_of_missing_tabs_in_tab_groups/
[3] https://www.googlecloudcommunity.com/gc/AppSheet-Q-A/Form-with-tabs-stops-working-after-last-Google-Chrome-update/m-p/613907
[4] https://www.galacticadvisors.com/research/google-chrome-fixes-empty-tabs-issue/
[5] https://blog.google/products/chrome/google-chrome-generative-ai-features-january-2024/
[6] https://chromewebstore.google.com/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl/support
[7] https://www.reddit.com/r/chrome/comments/14lhbb5/new_tabs_suddenly_stopped_working/
[8] https://www.youtube.com/watch?v=EsZ5bsfTYoI
[9] https://chromeos.dev/en/releases
[10] https://community.brave.com/t/new-update-broke-my-tab-groups/597163
[11] https://support.google.com/chrome/thread/321585142/google-apps-not-appearing-on-new-tab?hl=en
[12] https://www.yahoo.com/tech/google-chromes-latest-aims-organizing-124112482.html
[13] https://superuser.com/questions/1836200/how-to-revert-chromes-tab-ribbons-to-before-late-2024-march-version
[14] https://www.bitdefender.com/en-us/blog/hotforsecurity/upcoming-chrome-update-to-hide-personal-information-during-android-screen-shares
[15] https://www.bleepingcomputer.com/news/google/google-to-kill-chrome-sync-on-older-chrome-browser-versions/
[16] https://www.mail.com/blog/posts/how-to-restore-tabs/124/
[17] https://superuser.com/questions/1784714/google-chrome-new-tab-position-issues
[18] https://stackoverflow.com/questions/22901591/wait-for-chrome-tabs-update-tab-to-finish-loading
[19] https://www.pcmag.com/news/chrome-adds-performance-issue-alerts-for-memory-hogging-tabs

---
Answer from Perplexity: pplx.ai/share

**Comment by PlagueCZ** [comment]
I am now at work where I have `Version 118.0.5993.70 (Official Build) (64-bit)` and the issue still happens, so it's not a recent change.
I will try the other steps on my updated browser when I get to it then.

**Comment by harshayburadkar** [comment]
Thank you for reporting this issue. @petebrag @y-lee @PlagueCZ 
The issue is due to Chrome changing the underlying technology. It is not a code change in extension which is causing it.
The underlying technology is service workers which may cause the extension to sleep after 30 seconds of inactivity. 

I will still find a workaround/solution and update the extension to not forget the tab order after 30 seconds.

**Comment by xyzwilliamxyz** [comment]
Same here! Please, I love this extension ❤

**Comment by y-lee** [comment]
I am using as substitute https://microsoftedge.microsoft.com/addons/detail/quickey-%E2%80%93-the-quick-tab-s/mcjciddpjefdpndgllejgcekmajmehnd , https://fwextensions.github.io/QuicKey/ . @harshayburadkar , you may find examining it interesting. It does not have the tab order-forget issue, and implements some of the varying behavior based on timing of Quick key shortcut presses that makes CLUT preferable to other such extensions.

**Comment by sebwills** [comment]
Running on mac. After upgrading to the MV3 version I immediately noticed something similar: using the quick switch, Chrome sometimes brings up a Chrome PWA "app" I have running in a separate window (which I have not recently switched to), instead of the MRU tab.

**Comment by SornrasakC** [comment]
Hi, MV3 version is actually not made by the author. (reasons being I wanted the extension to get manifest version 3 earlier)

While the author is trying to solve the issue, I recommend going back to the original extension as the "not following standard" issue has been solved.

**Comment by gwo-001** [comment]
> I am using as substitute https://microsoftedge.microsoft.com/addons/detail/quickey-%E2%80%93-the-quick-tab-s/mcjciddpjefdpndgllejgcekmajmehnd , https://fwextensions.github.io/QuicKey/ . [@harshayburadkar](https://github.com/harshayburadkar) , you may find examining it interesting. It does not have the tab order-forget issue, and implements some of the varying behavior based on timing of Quick key shortcut presses that makes CLUT preferable to other such extensions.

quicKey work very well，thank you bro

**Comment by petebrag** [comment]
> Hi, MV3 version is actually not made by the author. (reasons being I wanted the extension to get manifest version 3 earlier)
> 
> While the author is trying to solve the issue, I recommend going back to the original extension as the "not following standard" issue has been solved.

No, it still doesn't work consistently.

**Comment by SornrasakC** [comment]
@petebrag Is this about MV3 version or the original one? I don't think the author has finish fixing this issue yet.

**Comment by petebrag** [comment]
old one. Although the extension is allowed on the Chrome store, it still doesn't work consistently, it seems. Am I wrong?

**Comment by SornrasakC** [comment]
The old one is correctly on this page, harshayburadkar is working on it as he have said.

When I say issue has been solved, I meant that the old extension is now allowed on store -- sorry if that confused you.

**Comment by harshayburadkar** [comment]
Update - I have pushed an update (version 2.1). It should become live after Chrome finishes the review process. I would love to hear if it fixed the issue once you all get your hands on it.

**Comment by omri-ratson** [comment]
Hi @harshayburadkar, I tried it on my Machine, Windows 11 with the latest Chrome version.
I installed it from the source (since I was really waiting for this fix 😊), but the key combination doesn't seem to work (Alt+W), I don't get any response from the browser when I try it.
When I click on the extension with the mouse, the tab change does appear to work as expected (the same as before the V3 manifest change).

**Comment by harshayburadkar** [comment]
> Hi [@harshayburadkar](https://github.com/harshayburadkar), I tried it on my Machine, Windows 11 with the latest Chrome version. I installed it from the source (since I was really waiting for this fix 😊), but the key combination doesn't seem to work (Alt+W), I don't get any response from the browser when I try it. When I click on the extension with the mouse, the tab change does appear to work as expected (the same as before the V3 manifest change).

Hello @omri-ratson  
Could you check the keyboard shortcut settings? It does get reset sometimes when updating.
And another thing to note, I think by tomorrow or Tuesday, v2.1 will be available. You should install that one since that has the fix to the issue many users have shared in this thread.

**Comment by omri-ratson** [comment]
> > > Hi [@harshayburadkar](https://github.com/harshayburadkar), I tried it on my Machine, Windows 11 with the latest Chrome version. I installed it from the source (since I was really waiting for this fix 😊), but the key combination doesn't seem to work (Alt+W), I don't get any response from the browser when I try it. When I click on the extension with the mouse, the tab change does appear to work as expected (the same as before the V3 manifest change).
> > 
> > Hello [@omri-ratson](https://github.com/omri-ratson) Could you check the keyboard shortcut settings? It does get reset sometimes when updating. And another thing to note, I think by tomorrow or Tuesday, v2.1 will be available. You should install that one since that has the fix to the issue many users have shared in this thread.
> 
> I've uninstalled the local and installed version 2.1 directly from the store.
> Works fine now with the keyboard shortcut as well.
> Thanks for the fix @harshayburadkar .
> 
> A small question, where can I view the extension shortcut settings?

To check and potentially modify Chrome extension keyboard shortcuts, navigate to chrome://extensions/shortcuts in your browser's address bar and then select the extension and its commands to view or change assigned shortcuts.

**Comment by y-lee** [comment]
> A small question, where can I view the extension shortcut settings?

@harshayburadkar , speaking of shortcuts, can you provide a guide akin to [what the QuicKey author does](https://fwextensions.github.io/QuicKey/ctrl-tab/) regarding inserting the Ctrl-Tab keybinding?

**Comment by mmlakin** [comment]
I was also having this exact issue constantly and the 2.1 update looks to have completely resolved it.

This extension is such a huge part of my daily workflow, @harshayburadkar thanks so much for all your efforts to get it updated and get this issue resolved so quickly! 🙏

**Comment by PlagueCZ** [comment]
Confirmed fixed on all version of chrome I have, thank you

**Comment by petebrag** [comment]
I installed 2.1 of original CLUT, here's what I'm experiencing: 

The keyboard shortcuts for activate the extension’ and ‘quick switch’ are the same function, that is,  they switch to the last tab and cycle through those two tabs. I can't seem to make it work otherwise or to increase the number of tabs that it switches. 

Switch backward DOES work, which is fantastic; however, switch forward does not work. It just goes to random tabs. 

Not sure if I'm doing something wrong, but I'm wondering if other users are having the issue with the switch forward as I am and exactly what those first two keyboard shortcuts do if not switch between two tabs.

**Comment by harshayburadkar** [comment]
@petebrag 
Can you check now, the issue should be fixed if you have the updated version 2.1.

**Comment by petebrag** [comment]
> [@petebrag](https://github.com/petebrag) Can you check now, the issue should be fixed if you have the updated version 2.1.

I am still just seeing that both Quick Switch and Activate the Extension both switch to the last tab and cycle through those two tabs.

**Comment by harshayburadkar** [comment]
> > [@petebrag](https://github.com/petebrag) Can you check now, the issue should be fixed if you have the updated version 2.1.
> 
> I am still just seeing that both Quick Switch and Activate the Extension both switch to the last tab and cycle through those two tabs.

Can you double check if you have the correct extension and version. It has been reported fixed by several users.

**Comment by NimoTh** [comment]
I am also still having this issue. Strangely, I think it works on my private profile but definitely not with my work profile. I am using CLUT 2.1 on both profiles. I have already tried removing and adding the extension again. Any other ideas how to solve this?

**Comment by harshayburadkar** [comment]
I could connect on a screen share to look at the issue. Alternatively you could record the screen while showing the issue but not sure if that will be enough. But we can try that as well.

**Comment by sebwills** [comment]
@NimoTh @petebrag Have you tried re-setting (e.g. changing and then changing back) the keyboard shortcuts assigned to those two actions in Manage Extensions -> Keyboard shortcuts -> CLUT? I _think_ I had the same issue after the upgrade, but it seemed to resolve after fiddling with the key assignments.

**Comment by NimoTh** [comment]
@sebwills I uninstalled and installed again, and this time it worked. CLUT works well for me now, again. Thanks a lot for your support!

**Comment by asgeirtj** [comment]
> [@harshayburadkar](https://github.com/harshayburadkar) , speaking of shortcuts, can you provide a guide akin to [what the QuicKey author does](https://fwextensions.github.io/QuicKey/ctrl-tab/) regarding inserting the Ctrl-Tab keybinding?

chrome.developerPrivate.updateExtensionCommand({
    extensionId: "cobieddmkhhnbeldhncnfcgcaccmehgn",
    commandName: "alt_switch_fast",
    keybinding: "Ctrl+Tab"
});

other commands are named alt_switch_slow_backward and alt_switch_slow_forward 

@y-lee

**Comment by y-lee** [comment]
Much appreciated!

**Comment by petebrag** [comment]
The extension is back to not working correctly. When I activate back or forward, it just goes to random locations. Is anyone having the same issue?

**Comment by harshayburadkar** [comment]
I would prefer to discuss it in a new issue @petebrag At this point it is highly unlikely it is related to the same issue. I will close this for now. Would you be able to record a video of it happening and attach it to the issue?
